### ISSUE TITLE
Query viewer example error

### ISSUE THREAD

**Issue by krishnaraj-creator** [Nhogs/popoto-examples#15] opened 2018-10-23 13:54 UTC
I get the following when running the Query viewer example. 

![image](https://user-images.githubusercontent.com/310055/47365438-8e4c9200-d6a9-11e8-8a5a-420aaa589e27.png)

**Comment by Popotojs** [comment] 2018-10-24 07:49
This issue was caused by latest change in v2.0.10, introducing an unsupported parameter in cypher query through rest API. It is fixed in version v2.0.11

Thanks

**Closed as completed by Popotojs** 2018-10-24 07:49 UTC
Labels: bug

**Comment by krishnaraj-creator** [comment] 2018-10-26 15:38
Thanks for correcting the error.
